# Generated by Django 3.2 on 2021-04-25 09:55

import apps.document.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('headers', models.JSONField(default=list, editable=False)),
                ('first_row', models.JSONField(default=dict, editable=False)),
                ('file', models.FileField(max_length=255, upload_to=apps.document.models.data_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])])),
                ('layout', models.JSONField(default=list)),
                ('background', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.document.models.bg_name)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.account')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
